### ISSUE TITLE
Make Class diagrams for database documents

### ISSUE THREAD

**Issue by gold1740** [Jaredcscott/3450-Project-Files-FooBar#13]

**Comment by gold1740** [comment]
Orders and Inventory items

**Comment by Braysen-Good** [comment]
Added document in [google drive](https://app.diagrams.net/#G12zKAP3TO-f-hMd-iUqvfyQJTw6pUZTGJ) types are also referenced in the [routes file](https://docs.google.com/document/d/1Lt4uz6eGjLfKLkAjOaCmpzopO6jLIijcxjBWrHlDcnY/edit).
