### ISSUE TITLE
Reorder A Past Order (Single Click)

### ISSUE THREAD

**Issue by Jaredcscott** [Jaredcscott/3450-Project-Files-FooBar#53]
story:
  1. A user navigates to order history 
  2. The user clicks the "order again" button on a previous order
  3. The user is prompted if they do not have enough money to place order
  4. The user is prompted if the order can not be placed
  5. If order succeeds, the user is notified

story points:
- [x] create order history page
- [x] create "order again" button
- [x] create user prompt for insufficient funds
- [x] create user prompt for unplacable order
- [x] create user prompt for success
- [x] prompt for pick up time of new order

**Comment by Braysen-Good** [comment]
story:
  1. A user navigates to order history 
  2. The user clicks the "order again" button on a previous order
  3. The user is prompted if they do not have enough money to place order
  4. The user is prompted if the order can not be placed
  5. If order succeeds, the user is notified

**Comment by Braysen-Good** [comment]
story points:
- [x] create order history page
- [x] create "order again" button
- [ ] create user prompt for insufficient funds
- [ ] create user prompt for unplacable order
- [x] create user prompt for success
