### ISSUE TITLE
Ability For Manager To Add New Inventory Types

### ISSUE THREAD

**Issue by Jaredcscott** [Jaredcscott/3450-Project-Files-FooBar#54]
story:
  1. manager goes to add inventory page
  2. manager fills out form
  3. manager clicks submit
  4. manager is informed of success or prompted with an error message and how to fix

Tasks:
  - [x] create routes on server to add new item to inventory
  - [x] create a react box of some type to input the details for a new item. This box will then be added to the appropriate page probably the inventory page.

**Comment by OmegaGiven** [comment]
If someone on the front end wants to take care of making the UI for this page I will finish up by populating the page with the things from the database

**Comment by Braysen-Good** [comment]
story:
  1. manager goes to add inventory page
  2. manager fills out form
  3. manager clicks submit
  4. manager is informed of success or prompted with an error message and how to fix
