### ISSUE TITLE
Account Creation Ability

### ISSUE THREAD

**Issue by Jaredcscott** [Jaredcscott/3450-Project-Files-FooBar#55]
Customer, Chef, Cashier, Manager

story points:
- [x] create registration page
- [x] create registration form
- [x] create user prompt for email taken
- [x] create user prompt for unequal password
- [x] creates the user in the back end

**Comment by Braysen-Good** [comment]
story:
  1. A user goes to the home page
  2. The user clicks the register button and gets redirected to registration form page
  3. The user fills in their name, email, password, and verify password
  4. The user clicks register
  5. The user is prompted to use forgot password instead if the email is already used
  6. The user is prompted to re-enter passwords and verify password if password and verify password are not the same
  7.  If nothing is wrong, the user is registered, signed in, and redirected to their homepage

**Comment by Braysen-Good** [comment]
story points:
- [ ] create registration page
- [ ] create registration form
- [ ] create user prompt for email taken
- [ ] create user prompt for unequal password
- [ ] creates the user in the back end
